name = "existence_higher_rank_ks"
version = "0.1.0"
defaultTargets = ["AugmentedHigherRankKS"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.24.0"

[[lean_lib]]
name = "MatrixSpencer"

[[lean_lib]]
name = "SeamlessKS"

[[lean_lib]]
name = "HigherRankKS"

[[lean_lib]]
name = "AugmentedHigherRankKS"
