import MatrixSpencer.RealRAMCircuit

/-!
# Safe primitive scalar formulas on positive inputs

`minimum` and `maximum` expand into scalar arithmetic and the square root of
a square, using the exact absolute-value identities. This is a macro language
for the existing primitive `Expr`; there are no new executable instructions.
Every expression generated by this grammar has positive value and safe
divisions/square roots on positive input registers.
-/
namespace MatrixSpencer.RealRAM
noncomputable section

def minimumExpr {ι : Type*} (a b : Expr ι) : Expr ι :=
  .div (.sub (.add a b) (.sqrt (.mul (.sub a b) (.sub a b)))) (.constant 2)
def maximumExpr {ι : Type*} (a b : Expr ι) : Expr ι :=
  .div (.add (.add a b) (.sqrt (.mul (.sub a b) (.sub a b)))) (.constant 2)

theorem minimumExpr_eval {ι : Type*} (a b : Expr ι) (v : ι → ℝ) :
    (minimumExpr a b).eval v = min (a.eval v) (b.eval v) := by
  simp only [minimumExpr,Expr.eval,←pow_two,Real.sqrt_sq_eq_abs,Rat.cast_ofNat]
  by_cases h : a.eval v ≤ b.eval v
  · rw [min_eq_left h,abs_of_nonpos (sub_nonpos.mpr h)]; ring
  · rw [min_eq_right (le_of_not_ge h),abs_of_nonneg (sub_nonneg.mpr (le_of_not_ge h))]; ring

theorem maximumExpr_eval {ι : Type*} (a b : Expr ι) (v : ι → ℝ) :
    (maximumExpr a b).eval v = max (a.eval v) (b.eval v) := by
  simp only [maximumExpr,Expr.eval,←pow_two,Real.sqrt_sq_eq_abs,Rat.cast_ofNat]
  by_cases h : a.eval v ≤ b.eval v
  · rw [max_eq_right h,abs_of_nonpos (sub_nonpos.mpr h)]; ring
  · rw [max_eq_left (le_of_not_ge h),abs_of_nonneg (sub_nonneg.mpr (le_of_not_ge h))]; ring

theorem minimumExpr_valid {ι : Type*} (a b : Expr ι) (v : ι → ℝ)
    (ha : a.Valid v) (hb : b.Valid v) : (minimumExpr a b).Valid v := by
  refine ⟨⟨⟨ha,hb⟩,⟨⟨⟨ha,hb⟩,⟨ha,hb⟩⟩,?_⟩⟩,trivial,by norm_num [Expr.eval]⟩
  exact mul_self_nonneg _

theorem maximumExpr_valid {ι : Type*} (a b : Expr ι) (v : ι → ℝ)
    (ha : a.Valid v) (hb : b.Valid v) : (maximumExpr a b).Valid v := by
  refine ⟨⟨⟨ha,hb⟩,⟨⟨⟨ha,hb⟩,⟨ha,hb⟩⟩,?_⟩⟩,trivial,by norm_num [Expr.eval]⟩
  exact mul_self_nonneg _

inductive PositiveFormula (ι : Type*) where
  | input : ι → PositiveFormula ι
  | constant : (q : ℚ) → (0 < q) → PositiveFormula ι
  | add : PositiveFormula ι → PositiveFormula ι → PositiveFormula ι
  | mul : PositiveFormula ι → PositiveFormula ι → PositiveFormula ι
  | div : PositiveFormula ι → PositiveFormula ι → PositiveFormula ι
  | sqrt : PositiveFormula ι → PositiveFormula ι
  | minimum : PositiveFormula ι → PositiveFormula ι → PositiveFormula ι
  | maximum : PositiveFormula ι → PositiveFormula ι → PositiveFormula ι

namespace PositiveFormula
variable {ι : Type*}

def toExpr : PositiveFormula ι → Expr ι
  | .input i => .input i
  | .constant q _ => .constant q
  | .add a b => .add a.toExpr b.toExpr
  | .mul a b => .mul a.toExpr b.toExpr
  | .div a b => .div a.toExpr b.toExpr
  | .sqrt a => .sqrt a.toExpr
  | .minimum a b => minimumExpr a.toExpr b.toExpr
  | .maximum a b => maximumExpr a.toExpr b.toExpr

def eval (f : PositiveFormula ι) (v : ι → ℝ) : ℝ := f.toExpr.eval v
def cost (f : PositiveFormula ι) : ℕ := f.toExpr.cost

@[simp] theorem eval_input (i : ι) (v : ι → ℝ) : (.input i : PositiveFormula ι).eval v = v i := rfl
@[simp] theorem eval_constant (q : ℚ) (h : 0 < q) (v : ι → ℝ) :
    (.constant q h : PositiveFormula ι).eval v = q := rfl
@[simp] theorem eval_add (a b : PositiveFormula ι) (v : ι → ℝ) :
    (add a b).eval v = a.eval v+b.eval v := rfl
@[simp] theorem eval_mul (a b : PositiveFormula ι) (v : ι → ℝ) :
    (mul a b).eval v = a.eval v*b.eval v := rfl
@[simp] theorem eval_div (a b : PositiveFormula ι) (v : ι → ℝ) :
    (div a b).eval v = a.eval v/b.eval v := rfl
@[simp] theorem eval_sqrt (a : PositiveFormula ι) (v : ι → ℝ) :
    (sqrt a).eval v = Real.sqrt (a.eval v) := rfl
@[simp] theorem eval_minimum (a b : PositiveFormula ι) (v : ι → ℝ) :
    (minimum a b).eval v = min (a.eval v) (b.eval v) := minimumExpr_eval _ _ _
@[simp] theorem eval_maximum (a b : PositiveFormula ι) (v : ι → ℝ) :
    (maximum a b).eval v = max (a.eval v) (b.eval v) := maximumExpr_eval _ _ _

theorem safe_and_positive (f : PositiveFormula ι) (v : ι → ℝ) (hv : ∀i,0<v i) :
    f.toExpr.Valid v ∧ 0 < f.eval v := by
  induction f with
  | input i => exact ⟨trivial,hv i⟩
  | constant q h => exact ⟨trivial,by change (0:ℝ)<q; exact_mod_cast h⟩
  | add a b ia ib => exact ⟨⟨ia.1,ib.1⟩,add_pos ia.2 ib.2⟩
  | mul a b ia ib => exact ⟨⟨ia.1,ib.1⟩,mul_pos ia.2 ib.2⟩
  | div a b ia ib => exact ⟨⟨ia.1,ib.1,ib.2.ne'⟩,div_pos ia.2 ib.2⟩
  | sqrt a ia => exact ⟨⟨ia.1,ia.2.le⟩,Real.sqrt_pos.mpr ia.2⟩
  | minimum a b ia ib =>
    exact ⟨minimumExpr_valid _ _ _ ia.1 ib.1,by simpa using lt_min ia.2 ib.2⟩
  | maximum a b ia ib =>
    exact ⟨maximumExpr_valid _ _ _ ia.1 ib.1,
      by simpa only [eval_maximum] using ia.2.trans_le (le_max_left (a.eval v) (b.eval v))⟩

theorem executes (f : PositiveFormula ι) (v : ι → ℝ) (hv : ∀i,0<v i) :
    Expr.Executes v f.toExpr (f.eval v) f.cost :=
  Expr.executes_of_valid _ _ (safe_and_positive f v hv).1

end PositiveFormula
end
end MatrixSpencer.RealRAM
